name: apple_shop
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  dotted_line: ^3.1.0
  dio: ^4.0.6
  dartz: ^0.10.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800

    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900

    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500

    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf
          weight: 700